micronaut:
  application:
    name: paymentGrpc
datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5432/qrcode`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USR:`postgres`}
    password: ${DB_PSW:`postgres`}
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update
BCB:
  url: ${CBC_URL:`http://localhost:8082/api/v1`}